spring:
  data:
    mongodb:
      uri: ${MONGO_URL}

payin:
  lock:
    url: "${PAYIN_URL}/lock"
  capture:
    url: "${PAYIN_URL}/capture"

payout:
  baseUrl: "${PAYOUT_URL}"
  path:
    topup: "/v1/topup"
    stream: "/v1/topups/stream"

compliance:
  check:
    url: "${COMPLIANCE_URL}/checkCompliance"

grpc:
  server:
    port: ${GRPC_SERVER_PORT}