spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017

payin:
  lock:
    url: "http://localhost:8090/lock"
  capture:
    url: "http://localhost:8090/capture"
payout:
  baseUrl: "http://localhost:8091"
  path:
    topup: "/v1/topup"
    stream: "/v1/topups/stream"

compliance:
  check:
    url: "http://localhost:8092/checkCompliance"
