payin:
  lock:
    url: "http://localhost:8090/lock"
  capture:
    url: "http://localhost:8090/capture"

payout:
  baseUrl: "http://localhost:8091"
  path:
    topup: "/v1/topup"
    stream: "/1/topups/stream"

compliance:
  check:
    url: "http://localhost:31144/checkCompliance"