spring:
  data:
    mongodb:
      uri: ${MONGO_URL}

payin:
  lock:
    url: "${PAYIN_URL}/lock"
  capture:
    url: "${PAYIN_URL}/capture"

payout:
  baseUrl: "http://payout:8091"
  path:
    topup: "/v1/topup"
    stream: "/v1/topups/stream"

compliance:
  check:
    url: "http://host.docker.internal:31144/checkCompliance"
