apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-service-deployment
  labels:
    app: compliance
spec:
  selector:
    matchLabels:
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
        - name: compliance-service
          image: localhost:32000/compliance-service:latest
          ports:
            - containerPort: 8092
          env:
            - name: MONGO_URL
              value: mongodb+srv://kniemiec:82e07B2VrahrY0iF@kniemiec-gcp-tests.r8lkfjh.mongodb.net/?retryWrites=true&w=majority
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-expose
spec:
  selector:
    app: compliance
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092