apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-orchestrator
  labels:
    app: orchestration
spec:
  selector:
    matchLabels:
      app: orchestration
  template:
    metadata:
      labels:
        app: orchestration
    spec:
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      containers:
        - name: transfer-orchestrator
          image: localhost:32000/transfer-orchestrator:latest
          ports:
            - name: http
              containerPort: 8080
              hostPort: 8080
            - name: grpc-server
              containerPort: 9999
              hostPort: 9999
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: PAYIN_URL
              value: http://10.152.183.145:8090
            - name: PAYOUT_URL
              value: http://10.152.183.254:8091
            - name: COMPLIANCE_URL
              value: http://10.152.183.228:8092
            - name: MONGO_URL
              value: mongodb+srv://kniemiec:82e07B2VrahrY0iF@kniemiec-gcp-tests.r8lkfjh.mongodb.net/?retryWrites=true&w=majority
            - name: GRPC_SERVER_PORT
              value: "9999"
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-orchestrator-service
spec:
  selector:
    app: orchestration
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-orchestrator-expose
spec:
  type: NodePort
  selector:
    app: orchestration
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
      name: http